[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/",
    "forge-std/=lib/forge-std/src/",
    "@prb-math/=lib/prb-math/src/",
    "@prb/math/=lib/prb-math/"
  ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
